### ISSUE TITLE
Missing Click ID variable in "Conversion" event type

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/taboola-tag#1]
When configuring the conversion in the Taboola Tag, I am missing the "Click ID" variable, which is the most important one.

![img](https://github.com/stape-io/taboola-tag/assets/6924386/18b9905f-98bc-4342-8cc9-37e961631324)

For the PageView event, there is a field in regards to "Click ID" (although not sure why it asks for the URL parameter name and not for the URL parameter value), but for the Conversion event, there is NO field in regards to "Click ID" in the template.

For reference: https://help.taboola.com/hc/en-us/articles/115006850567-How-to-Track-Conversions-Using-Server-to-Server-Integration-S2S

**Comment by ghost** [comment]
@alexgarciab the code is currently written to accept http requests only from browser client (i.e., from cookies) and not server client. We can raise a feature request to support server clients.

<img width="706" alt="Screenshot 2024-05-22 at 16 22 11" src="https://github.com/stape-io/taboola-tag/assets/5537334/55069640-aec7-4cd9-a401-7f7ce0a76dc9">

**Comment by alexgarciab** [comment]
Yes please. We are planning to use only server side events and with the current config, we can't fill the tag fields properly. This is already implemented in Outbrain tag, so it should be pretty similar.

**Comment by alexbub** [comment]
In 'PageView' tag mode, you need to specify the url parameter name where the click id will be available. When the tag is triggered in PageView mode and the click id will be available in the url - the 'taboola_cid' cookie will be set. This cookie value will be sent automatically along with the conversion.

UPD. Saw that you want to send s2s events, in that case you really need the ability to add your parameter to the click id.

**Comment by Bukashk0zzz** [comment]
Fixed

**Comment by alexgarciab** [comment]
@Bukashk0zzz [metadata.yaml](https://github.com/stape-io/taboola-tag/blob/main/metadata.yaml) file should be updated as well, right? I am not seeing the option to update the Taboola template directly in sGTM and I think it's due to not updating that file.

**Comment by Bukashk0zzz** [comment]
Meta data updated. soon it will be in the template gallery.
