### ISSUE TITLE
No "HTTP Request Details" in this Tag

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/taboola-tag#2]
Would it be possible to add "HTTP Request Details" for this Tag? Showing the different parameters of the Request & Response.
I know this is just a GET call to a URL with params, but it would be nice to have it.

![request](https://github.com/stape-io/taboola-tag/assets/6924386/679e9cea-6b0b-4590-b5e7-3f8a41ffd59f)

**Comment by alexgarciab** [comment]
So similar to how Outbrain tag is implemented, which do logs the requests:

![out](https://github.com/stape-io/taboola-tag/assets/6924386/959813c0-c0d0-49ed-91eb-616c5d8c6bbe)

**Comment by alexbub** [comment]
In your example, the tag didn't send the request. This is most likely due to the fact that there was no click id in your event. Without a click id, the data will not be sent.
If there is a click id and the request is sent, the request data will be displayed as in Outbrain.

**Comment by alexgarciab** [comment]
> In your example, the tag didn't send the request. This is most likely due to the fact that there was no click id in your event. Without a click id, the data will not be sent. If there is a click id and the request is sent, the request data will be displayed as in Outbrain.

Gotcha! Once this feature is added: https://github.com/stape-io/taboola-tag/issues/1 I will retest this again.
